default:
    image: ddlog/gitlab-ci:latest

variables:
    # Controls differential dataflow's eager compaction behavior
    DIFFERENTIAL_EAGER_MERGE: 100000
    # Some of our tests assume certain functionality to be available in
    # the CI pipeline (and will fail if that is not the case). This
    # variable is how this information is conveyed. Note that GitLab
    # already provides similar variables (e.g., `CI`; see
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html)
    # but we opted to have our own, in order to not depend on
    # potentially changing GitLab behavior as well as to achieve some
    # form of independence of the underlying CI pipeline.
    IS_CI_RUN: 1
    # Tell ./test.sh script not to redirect test stdout and stderr to file.
    NO_STD_REDIRECT: 1

# Template for tests that expect ddlog to be in the $PATH.
.install-ddlog:
    before_script:
        - stack install

# Test Rust template only.
test-rust:
    script:
        - ./test.sh crates
        - ./test.sh tcp_channel

# Run individual stack-based tests, when possible combining them with Java tests
# that depend on the same DDlog program.
test-tutorial:
    script: ./test.sh tutorial

test-rust-api:
    script: ./test.sh rust_api

# Test individual libraries

test-libs:
    extends: .install-ddlog
    script: ./test.sh libs

test-server_api:
    extends: .install-ddlog
    script: ./test.sh server_api

test-simple:
    tags:
        - ddlog-ci-1
    script: ./test.sh simple

test-simple2:
    script: ./test.sh simple2

test-modules:
    script: ./test.sh modules

test-ovn-ftl:
    script: ./test.sh ovn_ftl

test-ovn:
    script: ./test.sh ovn_mockup

test-path:
    script:
        - ./test.sh negative
        - ./test.sh path

test-souffle0:
    extends: .install-ddlog
    tags:
        - ddlog-ci-1
    script: ./test.sh static_analysis 

test-redist:
    extends: .install-ddlog
    tags:
        - ddlog-ci-1
    script:
        - ./test.sh redist
        - ./test.sh java1
        - ./test.sh flatbuf0

test-span_string:
    extends: .install-ddlog
    script:
        - ./test.sh span_string
        - ./test.sh java3

test-output-internal:
    script: ./test.sh stream

# All other Java tests.
test-span_uuid:
    extends: .install-ddlog
    script:
        - ./test.sh span_uuid
        - ./test.sh java0

test-java1:
    extends: .install-ddlog
    script:
        - ./test.sh java2
        - ./test.sh java4

# these tests are currently failing (#372)
#test-java2:
#    extends: .install-ddlog
#    script:
#        - (cd java/test5 && ./run.sh)
#        - (cd java/test6 && ./run.sh)

test-flatbuf:
    extends: .install-ddlog
    tags:
        - ddlog-ci-1
    script: ./test.sh flatbuf1

# Template for souffle tests
.test-imported-souffle:
    extends: .install-ddlog
    tags:
        - ddlog-ci-1

# Tests from the souffle github repo.
test-imported-souffle-tests1:
    extends: .test-imported-souffle
    script: ./test.sh souffle_tests1

test-imported-souffle-tests2:
    extends: .test-imported-souffle
    script: ./test.sh souffle_tests2

test-imported-souffle-tests3:
    extends: .test-imported-souffle
    script: ./test.sh souffle_tests3

test-imported-souffle-tests4:
    extends: .test-imported-souffle
    script: ./test.sh souffle_tests4

test-imported-souffle-tests5:
    extends: .test-imported-souffle
    script: ./test.sh souffle_tests5

test-imported-souffle-tests6:
    extends: .test-imported-souffle
    script: ./test.sh souffle_tests6

test-imported-souffle-tests7:
    extends: .test-imported-souffle
    script: ./test.sh souffle_tests7

# Test DDlog code from the Declarative Cluster Management project
test-dcm:
    extends: .install-ddlog
    tags:
        - ddlog-ci-1
    script: ./test.sh dcm

# Torture-test optimized version of redist
test-redist_opt:
    extends: .install-ddlog
    tags:
        - ddlog-ci-2
    script: ./test.sh redist_opt

# Test ovn-northd-ddlog
test-ovn-northd:
    extends: .install-ddlog
    # Don't use eager merging, as northd tends to perform many small
    # transactions, making things slow.
    variables: {}
    tags:
        - ddlog-ci-2
    script: ./test.sh ovn_check

# Test antrea
test-antrea:
    extends: .install-ddlog
    tags:
        - ddlog-ci-1
    script: ./test.sh antrea_check

# Test the SQL-to-DDlog compiler.
test-sql:
    extends: .install-ddlog
    script: ./test.sh sql

# Test Go bindings
test-golang:
    extends: .install-ddlog
    script: ./test.sh go

# Test stream relations.
test-stream:
    extends: .install-ddlog
    script: ./test.sh stream
